### ISSUE TITLE
[FEATURE] 如何支持plantuml

### ISSUE THREAD

**Issue by whuwangyong** [hugo-fixit/FixIt#116]
### Describe the feature you want 描述你的功能需求

我在网上找到一篇文章：[在 Hugo 博客上使用 PlantUML](https://mogeko.me/posts/zh-cn/083/)

试了无效，请问应该怎么操作？
谢谢！

**Comment by Lruihao** [comment]
生成时序图这些，现在可以用 mermaid

https://fixit.lruihao.cn/zh-cn/theme-documentation-extended-shortcodes/#5-mermaid


这个需求，我有时间再研究一下

**Comment by qjebbs** [comment]
这个跟我做 [vscode-plantuml](https://github.com/qjebbs/vscode-plantuml) 预览面临的情况类似的，甚至更受限。

PlantUML 运行在 Java 环境，要取得渲染好的图片：
- 要么本地启一个 java 进程渲染（作为一个主题，不可能做到）
- 要么使用 PlantUML 服务器。
    - 若部署自己的服务器，并配置服务器 URL 在主题中。使用门槛太高了。
    - 若使用[官方服务器](https://www.plantuml.com/plantuml)，不支持 POST，只支持 GET，会受限于 URL 长度；用户还可能有数据隐私方面的担心。

总之，我觉得 PlantUML 不合适这个场景，mermaid 挺好
