### ISSUE TITLE
[BUG] Nav 中选择语言和切换主题按钮不显示手形光标

### ISSUE THREAD

**Issue by boh5** [hugo-fixit/FixIt#193]
### Describe the bug 描述你遇到的错误

鼠标放在 `Nav` 中`选择语言`和`切换主题`按钮上，不显示`手形光标`，显示的是`箭头光标`。

### Expected behavior 期待的行为

`选择语言`和`切换主题`按钮像其他按钮一样显示`手形光标`。

### Screenshots 屏幕截图

![Imgur](https://i.imgur.com/6UdmznX.png)

**Comment by Lruihao** [comment]
https://fixit-m8i91vuxx-x-cell.vercel.app/
