### ISSUE TITLE
[BUG]  ver0.2.16, image shortcode loses the support for .svg files

### ISSUE THREAD

**Issue by seekzzh** [hugo-fixit/FixIt#210]
### Describe the bug 描述你遇到的错误

Error: Error building site: failed to render shortcode "image": failed to process shortcode: "F:\hugo_site\themes\FixIt\layouts\shortcodes\image.html:28:6": execute of template failed: template: shortcodes/image.html:28:6: executing "shortcodes/image.html" at <partial "plugin/image.html" $options>: error calling partial: "F:\hugo_site\themes\FixIt\layouts\partials\plugin\image.html:7:32": execute of template failed: template: partials/plugin/image.html:7:32: executing "partials/plugin/image.html" at *<.Width>: error calling Width: this method is only available for raster images.* To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}

### Expected behavior 期待的行为

Optimize the code in `FixIt\layouts\partials\plugin\image.html`

**Comment by Lruihao** [comment]
When I use the image shortcode for loading svg file as follow, it seems available.

```
{{< image src="/fixit.min.svg" >}}
```

@seekzzh Could you provide me with your svg picture and usag case?

**Comment by seekzzh** [comment]
Hi,

Thanks for the update!

I tried it again just now and it works using the following shortcode.
`{{< image src="./Basic_principles_of_photography.svg" title="Camera lens" width="100%">}}`

But it will throw errors using the following code,
`{{< image src="Basic_principles_of_photography.svg" title="Camera lens" width="100%">}}`
The errors won't happen when using "xxx.png".

The following code also doesn't work properly.
`{{< image src="/Basic_principles_of_photography.svg" title="Camera lens" width="100%">}}`









![Basic_principles_of_photography](https://user-images.githubusercontent.com/43107024/194052374-95edbab8-5e55-40a7-b0ac-60ec5eaafaf5.svg)

**Comment by Lruihao** [comment]
Okay, I catch it! I'll fix it as soon as possible.

Thanks ❤️

**Comment by Lruihao** [comment]
resolved
