### ISSUE TITLE
建议增加打赏功能，可参考这个博文操作

### ISSUE THREAD

**Issue by Charlie-king** [hugo-fixit/FixIt#216]
### Describe the feature you want 描述你的功能需求

建议在主题模板里增加打赏功能，可参考这个https://cywhat.cn/Loveit%E4%B8%BB%E9%A2%98%E5%BC%80%E5%90%AF%E6%96%87%E7%AB%A0%E8%B5%9E%E8%B5%8F/

### Useful reference 有价值的参考

https://cywhat.cn/Loveit%E4%B8%BB%E9%A2%98%E5%BC%80%E5%90%AF%E6%96%87%E7%AB%A0%E8%B5%9E%E8%B5%8F/

**Comment by Charlie-king** [comment]
我整理写了文章，更详细清晰一些。https://zhjin.eu.org/posts/202210/2022-10-4-added-reward-function/

**Comment by CollieIsCute** [comment]
@Charlie-king I just get a 404 from the [article](https://zhjin.eu.org/posts/202210/2022-10-4-added-reward-function/) you gave.

**Comment by Charlie-king** [comment]
@CollieIsCute 
I changed the Permalinks，You can see the new address here：(https://zhjin.eu.org/posts/2022-10-04-added-reward-function/）

**Comment by Lruihao** [comment]
resolved with #234

**Comment by Lruihao** [comment]
- [ ] add reward shortcode support
