### ISSUE TITLE
[FEATURE] 增加一个类似wiki的功能

### ISSUE THREAD

**Issue by ericting** [hugo-fixit/FixIt#219]
### Describe the feature you want 描述你的功能需求

如题,能不能增加像这个[网站](https://ankmak.com/tech/arch/intro.html)一样的功能，可以理解为在网站头部栏目中添加wiki文档分类，而不是简单的一篇文章，而是一个分类，其主要就是增加了分类下的左边的目录 ~~（不太会描述）~~

### Useful reference 有价值的参考

https://ankmak.com/tech/arch/intro.html

**Comment by Lruihao** [comment]
用途定位不同，该功能不适合加到 **博客** 类主题中，文档类，应该换 vuepress 类的工具或这换 hugo 专门的主题
