### ISSUE TITLE
增加相关文章功能

### ISSUE THREAD

**Issue by zyyjade** [hugo-fixit/FixIt#227]
### Describe the feature you want 描述你的功能需求

你好，请问是否可以在文章内增加系列 series 或文末增加相关文章功能吗？
![示例](https://user-images.githubusercontent.com/101989311/195363489-3906a761-81b6-40e3-ac08-b2a75b6980fc.png)

### Useful reference 有价值的参考

- [Hugo series](https://gohugo.io/content-management/taxonomies/#example-adding-a-custom-taxonomy-named-series)
- [DoIt 系列样式](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/)

**Comment by Lruihao** [comment]
系列文章，我总感觉和分类的差别不大，而且 DoIt 有现成，有这方面需求的话，可以直接换 DoIt 就好。

---

相关文章，有打算实现。

**Comment by Lruihao** [comment]
https://gohugo.io/content-management/related/
