### ISSUE TITLE
[FEATURE] add Google CSE support

### ISSUE THREAD

**Issue by 1an8r0wn** [hugo-fixit/FixIt#244]
### Describe the feature you want 描述你的功能需求

希望能够添加 Google CSE 搜索支持。

**Comment by Lruihao** [comment]
[Programmable Search Engine (formerly CSE)](https://programmablesearchengine.google.com/)

**Comment by Lruihao** [comment]
[CSE 支持文档](https://pre.fixit.lruihao.cn/zh-cn/guides/cse-support/)
