### ISSUE TITLE
[BUG] Hashtag character in tags, can it be escaped ?

### ISSUE THREAD

**Issue by Kapusch** [hugo-fixit/FixIt#245]
### Describe the bug 描述你遇到的错误

Hi, first I would like to thank you for maintaining this theme which I'm experimenting for few weeks.

I encountered the following issue where my tag is not rendered in the UI:
<img width="86" alt="image" src="https://user-images.githubusercontent.com/9576733/202562296-14c18ea0-a186-42ef-9274-612fc9e65326.png">

And I think it's because it contains a hashtag character inside, as you can see from my Front Matter property:
`Tags: ["C# markup","Grid"]`

### Expected behavior 期待的行为

All my tags should be rendered and any unexpected character should be escaped.
Do you think it should be fixed in the template itself or Is there any workaround ?

**Comment by Lruihao** [comment]
@Kapusch Thanks for your feedback, this bug has been fixed.

**Comment by Lruihao** [comment]
reopen with #246

**Comment by Lruihao** [comment]
resolved

**Comment by Kapusch** [comment]
Hi @Lruihao , thank you for your quick fix !
I just gave a try and now the hashtag character is well escaped.

However, I wonder if I should do something else regarding the commas that have disappear, or is it a side-effect bug ?
<img width="150" alt="image" src="https://user-images.githubusercontent.com/9576733/202897136-22f103ce-2b2f-453f-9394-625a3138eef8.png">

As a reminder, here is my front matter property:
`Tags: ["C# markup","Grid"]`

**Comment by Lruihao** [comment]
> However, I wonder if I should do something else regarding the commas that have disappear, or is it a side-effect bug ?

@Kapusch This is not a bug cause of your local browser caches old css style. Clear the browser cache, it will be okay.

**Comment by Kapusch** [comment]
Thanks for your help, I thought I already cleared it, so maybe it's after I relaunched the website with Hugo serve command.
It's all good now 👍
