### ISSUE TITLE
[BUG] tags和category包含中文时显示为空

### ISSUE THREAD

**Issue by leafney** [hugo-fixit/FixIt#246]
### Describe the bug 描述你遇到的错误

使用最新的 `master` 分支提交 203de93 ，tags和category中包含中文时显示为空

通过测试发现这个问题和提交 #245 有关，退回到该提交之前一个版本 88ec9f6 后，中文能够正常显示出来

**Comment by Lruihao** [comment]
reopen #245

**Comment by Lruihao** [comment]
已修复 https://github.com/hugo-fixit/FixIt/commit/d31215044de79cecf2fa1e90273cb66ea2f5f845
