### ISSUE TITLE
[FEATURE] Add Isso Commenting server support.

### ISSUE THREAD

**Issue by GraciousGpal** [hugo-fixit/FixIt#248]
### Describe the feature you want 描述你的功能需求

Isso is Commenting system similar to Disqus but it is self hosted and private.

### Comments written in Markdown

Users can edit or delete own comments (within 15 minutes by default).

Comments in moderation queue are not publicly visible before activation.

### SQLite backend

Because comments are not Big Data.

### Disqus & WordPress Import

You can migrate your Disqus/WordPress comments without any hassle.

### Configurable JS client

Embed a single JS file, 65kB (20kB gzipped) and you are done.

Supports Firefox, Safari, Chrome and IE10.

### Useful reference 有价值的参考

https://isso-comments.de/

**Comment by Lruihao** [comment]
Due to limited energy and consideration for the simplicity of the FixIt theme, we are no longer considering adding a built-in comment system.

> [!NOTE]
> The openness of FixIt theme is sufficient to meet the needs of user-defined comment systems (such as custom JS, creating Hugo theme components, etc.)
