### ISSUE TITLE
[FEATURE] Add Cactus Comments support

### ISSUE THREAD

**Issue by d-baer** [hugo-fixit/FixIt#250]
### Describe the feature you want 描述你的功能需求

I'd like to have [Cactus Comments](https://cactus.chat/) support in FixIt. As far as I have seen Cactus is able to be integrated in Hugo (https://cactus.chat/docs/integrations/hugo/). Anything FixIt can do to supoort that? Or is there nothing to do since it is integratable in Hugo without the help of FixIt

**Comment by Lruihao** [comment]
Due to limited energy and consideration for the simplicity of the FixIt theme, we are no longer considering adding a built-in comment system.

> [!NOTE]
> The openness of FixIt theme is sufficient to meet the needs of user-defined comment systems (such as custom JS, creating Hugo theme components, etc.)
