### ISSUE TITLE
GitHub actions build error

### ISSUE THREAD

**Issue by divazone** [hugo-fixit/FixIt#268]
### Describe the bug 描述你遇到的错误

為何在使用github actions build是會出現下列錯誤

Liquid Exception: Liquid syntax error (line 1): Variable '{{< style "img { height: 1.25rem; }' was not properly terminated with regexp: /\}\}/ in themes/FixIt/docs/content/about/index.en.md

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/3491934/213351857-96a371ac-398d-4ecd-81ce-e21618e3ef22.png)

**Comment by JamesFlare1212** [comment]
你的语法不小心写错了，shortcode记得以`>}}`结尾

你写的是

```
{{< style "img { height: 1.25rem; }
```

改成差不多这个样子

```
{{< style "img { height: 1.25rem; }" >}}
```

这是一个例子

```
{{< style "text-align:right; strong{color:#00b1ff;}" >}}
This is a **right-aligned** paragraph.
{{< /style >}}
```

**Comment by divazone** [comment]
我是用submodule的方式引入了應該不會有寫錯的問題才是...

**Comment by divazone** [comment]
> 你的语法不小心写错了，shortcode记得以`>}}`结尾
> 
> 你写的是
> 
> ```
> {{< style "img { height: 1.25rem; }
> ```
> 
> 改成差不多这个样子
> 
> ```
> {{< style "img { height: 1.25rem; }" >}}
> ```
> 
> 这是一个例子
> 
> ```
> {{< style "text-align:right; strong{color:#00b1ff;}" >}}
> This is a **right-aligned** paragraph.
> {{< /style >}}
> ```

我是用submodule的方式引入了應該不會有寫錯的問題才是...

**Comment by Lruihao** [comment]
这个和docs的内容格式应该没关系，应该是action的配置问题，检查一下hugo版本和相关命令？

**Comment by divazone** [comment]
我的語法如下，是說有看到有人反應說ubuntu22.04跟git pages所使用的jekyll相依性爆炸，不知是否跟這個有關係就是？

`name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public `

**Comment by divazone** [comment]
> 这个和docs的内容格式应该没关系，应该是action的配置问题，检查一下hugo版本和相关命令？

我的語法如下，是說有看到有人反應說ubuntu22.04跟git pages所使用的jekyll相依性爆炸，不知是否跟這個有關係就是？

`
name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 
`

**Comment by Lruihao** [comment]
```
  - name: Setup Hugo
    uses: peaceiris/actions-hugo@v2
    with:
      hugo-version: 'latest'
      # extended: true
```
我看你的 hugo 擴展版本是註釋掉的，FixIt 主題是需要擴展版本的，你打開試試。

我對 actions 其實也了解不多，你可以看看下面兩個倉庫的 actions 配置：

- Lruihao/hugo-blog
- huho-fixit/docs

**Comment by divazone** [comment]
不好意思，這邊我複製到之前用的版本，我實際build的時候註解是有確實拿掉的就是

**Comment by Lruihao** [comment]
> 不好意思，這邊我複製到之前用的版本，我實際build的時候註解是有確實拿掉的就是

那我過幾天試試看吧，你就是用的 fixit 這個倉庫的結構，然後改成 github actions 構建的嗎

**Comment by divazone** [comment]
是的，那就麻煩您也測試看看了

**Comment by divazone** [comment]
後來發現是我自己分支名稱設定錯誤了，應該是沒有問題了。

**Comment by Lruihao** [comment]
> 後來發現是我自己分支名稱設定錯誤了，應該是沒有問題了。

👌
