### ISSUE TITLE
Error: Error building site: TOCSS: failed to transform "css/style.scss" (text/x-scss): "D:/shekharverma/themes/FixIt/assets/css/_core/_common.scss:58:23": Undefined variable: "$orders".[BUG] Some problem ...

### ISSUE THREAD

**Issue by shekhuverma** [hugo-fixit/FixIt#281]
### Describe the bug 描述你遇到的错误

I Updated to latest version of your theme but got this error when running command "hugo server" 
I commented 
```
@each $key, $value in $orders {
  .order-#{$key} {
    order: #{$value} !important;
  }
}
```
in file /themes/FixIt/assets/css/_core/_common.scss and it worked

### Expected behavior 期待的行为

Hugo server will be able to run without any error

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/23568292/216811583-5021086a-bd7d-420a-8e91-6a12ae0fb218.png)

### Build Environment 构建环境

- OS : windos 10
- Theme version 2.17 release 
- Hugo Version - hugo v0.108.0-a0d64a46e36dd2f503bfd5ba1a5807b900df231d+extended windows/amd64 BuildDate=2022-12-06T13:37:56Z VendorInfo=gohugoio

**Comment by Lruihao** [comment]
Please check if this file is included in your project: `assets/css/_partials/_maps/_utilities.scss`. Or could you show me your project source code?

**Comment by shekhuverma** [comment]
Yes , the file is their in the source code.
But its still showing this error

**Comment by Lruihao** [comment]
> Yes , the file is their in the source code. But its still showing this error

I'm sorry:(, I can't reproduce this bug.

**Comment by shekhuverma** [comment]
![image](https://user-images.githubusercontent.com/23568292/217778831-3b26e232-ca2c-4339-b658-e23cb3355cf8.png)
This is the error i'm getting now
But the same config file and contents folder is working on the older version of FixIt theme.
Can you please help me with fixing this issue

**Comment by Lruihao** [comment]
if your using FixIt version >=v0.2.17, you should change the parameter footer.siteTime of your config as below:

```toml
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" # e.g. "2021-12-18T16:15:22+08:00"

```

**Comment by shekhuverma** [comment]
It fixed the footer related error but the orignal issue remains the same.
![image](https://user-images.githubusercontent.com/23568292/217799430-8c29b194-5d2d-478d-8a3e-12ebcd53c61b.png)

**Comment by shekhuverma** [comment]
The issue was due to my custom CSS. It was confilicting with the same.
It's resolved now
Thankyou
