### ISSUE TITLE
[FEATURE] 侧边栏添加 最近更新的文章列表，或者最新评论列表

### ISSUE THREAD

**Issue by geekswg** [hugo-fixit/FixIt#291]
### Describe the feature you want 描述你的功能需求

在电脑的版面上 ，hugo主题的左边的侧边栏基本上是空的，希望添加一些有用的信息

- 1.固定显示悬浮显示作者的信息。
- 2.显示最新文章列表
- 3.最新评论列表。

这样整个页面在电脑端看起来比较好一些，小小意见，仅供参考。

**Comment by Lruihao** [comment]
左边留出的位置就是自定义区，你可以用来做这些功能也可以添加广告位等等，主题中打算继续保留这片空白供不同的用户自定义。

**Comment by geekswg** [comment]
好的&nbsp;


Gavin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hugo-fixit/FixIt] [FEATURE] 侧边栏添加 最近更新的文章列表，或者最新评论列表 (Issue #291)





 
左边留出的位置就是自定义区，你可以用来做这些功能也可以添加广告位等等，主题中打算继续保留这片空白供不同的用户自定义。

**Comment by Lruihao** [comment]
自定义文件路径可见参数 params.customFilePath
