### ISSUE TITLE
[BUG] metingJs 引入音乐后 目录链接失效

### ISSUE THREAD

**Issue by geekswg** [hugo-fixit/FixIt#292]
### Describe the bug 描述你遇到的错误

使用dev分支主题。
在自定义aside.html 中引入 meting音乐后，文章中的目录链接就失效，点击后没有反应。
注释掉 meting 音乐后，目录恢复正常

**Comment by Lruihao** [comment]
侧栏里具体写了什么内容，控制台有无报错？

**Comment by geekswg** [comment]
报错信息：


hm.baidu.com/hm.gif?…E5%B0%91%E4%BE%A0:1 
 
 GET https://hm.baidu.com/hm.gif?hca=DA2E0442C8301E7D&amp;cc=1&amp;ck=1&amp;cl=24-bit&amp;ds=192…1%2598%25E8%25A6%2581&amp;tt=Hugo-Admonition%20-%20%E6%AF%95%E5%B0%91%E4%BE%A0 net::ERR_SSL_PROTOCOL_ERROR
Image(异步)
***@***.***?d25f1e053205bf…562f33365fef04d7:27
***@***.***?d25f1e053205bf…562f33365fef04d7:63
***@***.***?d25f1e053205bf…562f33365fef04d7:54
***@***.***?d25f1e053205bf…562f33365fef04d7:53
***@***.***?d25f1e053205bf…562f33365fef04d7:52
***@***.***:116
***@***.***:101
setTimeout(异步)
***@***.***:93
***@***.***:51
***@***.***:140
***@***.***:70


&nbsp;


Gavin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月26日(星期天) 下午2:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hugo-fixit/FixIt] [BUG] metingJs 引入英语 目录链接失效 (Issue #292)





 
侧栏里具体写了什么内容，控制台有无报错？

**Comment by geekswg** [comment]
我在本地测试好像没有报错，目录就是点了 没有跳转，地址变了。
注释掉 meting 音乐后，目录链接正常。
aside 添加的代码如下
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
<script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
<!-- require MetingJS -->
<script src="https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js"></script>
<meting-js
	server="netease"
	type="playlist" list-folded=true order="random"
	id="6678743774" volume="0.2" list-max-height="340px" >
</meting-js>
```

**Comment by geekswg** [comment]
看别人说是 Aplayer导致的,请大佬参考
https://blog.wangriyu.wang/2018/06-Aplayer.html

**Comment by Lruihao** [comment]
已处理

**Comment by geekswg** [comment]
请问 [v0.2.18](https://github.com/hugo-fixit/FixIt/milestone/7) 发布了吗，我现在为什么使用mater或者dev版本编译报错，切到0.2.17，才能正常启动。
![image](https://user-images.githubusercontent.com/31149899/222657125-39089fcf-269f-41f2-94e4-1eeecc9d7514.png)
请问改了什么配置吗

**Comment by Lruihao** [comment]
中文内容标题后的链接仍然存在bug。
