### ISSUE TITLE
[FEATURE] 添加 revolvermaps

### ISSUE THREAD

**Issue by RoderickChan** [hugo-fixit/FixIt#293]
### Describe the feature you want 描述你的功能需求

这个功能很有趣，可以用地球仪显示网站访客的分布 https://www.revolvermaps.com/
如果方便的话，希望作者可以添加这项功能

**Comment by Lruihao** [comment]
此功能过于个性化，不适合内置于主题中，有兴趣的可自行开发成插件引入。
