### ISSUE TITLE
[BUG] 搜索不支持中文，搜索英文正常

### ISSUE THREAD

**Issue by qq516249940** [hugo-fixit/FixIt#294]
### Describe the bug 描述你遇到的错误
使用搜索类型为：lunr

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/19165935/221787811-0286fcb6-81d1-4db6-bc54-0c2615cb4dbc.png)
![image](https://user-images.githubusercontent.com/19165935/221787859-c20e5ffb-4f34-4f5c-bc47-a0dda3c7a094.png)

### Build Environment 构建环境

ubuntu 22.04
$ hugo version
hugo v0.110.0+extended linux/amd64 BuildDate=unknown

### Additional Information 补充信息

我更换了fuse 类型，使用能搜索中文了！

**Comment by geekswg** [comment]
lunr要配置json，你这个问题解决了，可以把issue，close掉了
