### ISSUE TITLE
[BUG] 留言，友链等页面，开启评论后，标题抖动动画会失效

### ISSUE THREAD

**Issue by willow-yang** [hugo-fixit/FixIt#304]
### Describe the bug 描述你遇到的错误

![image](https://user-images.githubusercontent.com/66243023/224255576-7fcf19c6-81c1-4f15-8c23-c2b1383363a6.png)
当我把markdown文件的front matter的comment设置为false的时候，标题动画会正常展示，设置成true的时候，标题动画就会失效，而且标题的标签还会莫名其妙的亮一下
具体页面请看这里 [标题动画失效页面](https://willowyang.cn/friends/)

博客示例也有这种情况哦 [博客地址](https://lruihao.cn/guestbook/)

注意！！！第一次访问可能没有问题，重复访问几次就能复现

**Comment by Lruihao** [comment]
这个是 valine 样式和 animate.css 关键帧 `pulse` 样式冲突导致的

https://github.com/xCss/Valine/blob/a4c3d96b1492ed20a17a74162997309083014c74/src/index.scss#L475-L479

https://github.com/animate-css/animate.css/blob/3235f27325ebc721fc4f8435d3c2d436642278bc/source/attention_seekers/pulse.css#L3-L15

**Comment by Lruihao** [comment]
resolved
