### ISSUE TITLE
[BUG] toc 在页面包含大量 H4 以下标题时无法对齐，且滚动时会发生数组index溢出

### ISSUE THREAD

**Issue by maling-one** [hugo-fixit/FixIt#305]
### Describe the bug 描述你遇到的错误

toc 在页面包含大量 H4 以下标题时，无法对齐，且滚动时会发生数组index溢出 
`theme.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')`

### Expected behavior 期待的行为

由于 toc 只支持H3以上标题，所以希望滚动时忽略H4以下的标题

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/105653278/224494708-aa2230e6-e09c-4c2f-9700-0715812dcbbd.png)
![image](https://user-images.githubusercontent.com/105653278/224494758-a0d54aaa-c337-4c2f-9eaa-7e582a51da99.png)

**Comment by Lruihao** [comment]
已修复可能的报错，或者修改 markup 配置
```toml
[tableOfContents]
  startLevel = 2
  endLevel = 6
```
