### ISSUE TITLE
[BUG] 使用默认配置开启评论功能，不生效

### ISSUE THREAD

**Issue by maling-one** [hugo-fixit/FixIt#307]
### Describe the bug 描述你遇到的错误

使用从主题根目录拷贝出来的 config.toml，把配置打开：

![image](https://user-images.githubusercontent.com/105653278/225047851-371ea6e2-226c-48d5-a28d-95bb3f68d912.png)

部署后不生效

### Expected behavior 期待的行为

可以生效

### Screenshots 屏幕截图

不启用与启用  gitalk 情况下

[params.page.comment.gitalk]
        enable = true

生成的 html 对比如下：

![image](https://user-images.githubusercontent.com/105653278/225048588-16dd5bfc-afe0-4023-9d79-d6fadd9f1966.png)

**Comment by maling-one** [comment]
没用自定义任何与 comment 相关的内容
![image](https://user-images.githubusercontent.com/105653278/225049212-21c52db8-7cd5-4e7e-aac4-beea300adaa6.png)

**Comment by Lruihao** [comment]
artalk的server配置了吗？

**Comment by maling-one** [comment]
> 

目前试过两种配置。

配置1：
![image](https://user-images.githubusercontent.com/105653278/225164184-75cbc9f3-6f52-4353-b0f5-b73280cef9e6.png)

配置2：
![image](https://user-images.githubusercontent.com/105653278/225164258-272f74a0-b321-4f80-a12f-5bd16a6c9d9a.png)

都没生效，而且 hugo 编译生成的 html 都没变化

**Comment by Lruihao** [comment]
由于本地 development 环境的限制， 评论系统 , CDN 和 fingerprint 不会在 development 环境下启用。

你可以使用 hugo server -e production 命令来开启这些特性。

**Comment by maling-one** [comment]
如果不是bug就先关闭我自己研究下吧。。

目前我用了你说的这个命令启动 
![image](https://user-images.githubusercontent.com/105653278/225185566-1677676c-5e7c-4d7e-8f2f-eab28c89adba.png)
![image](https://user-images.githubusercontent.com/105653278/225185636-a901eda2-5545-4b19-9910-d597f1bde727.png)
发现还是没生效，有什么需要注意的事项吗？

**Comment by Lruihao** [comment]
应该不是bug，你用的这些评论都有人在用。你把缓存去掉试试。

**Comment by maling-one** [comment]
ok
