### ISSUE TITLE
[BUG] 页面md中的前置参数authorLink没有效果

### ISSUE THREAD

**Issue by geekswg** [hugo-fixit/FixIt#310]
### Describe the bug 描述你遇到的错误

author: Cursor
authorLink: https://www.cursor.so/

配置后，作者是灰色的不可点击，没有链接效果

使用主题分支DEV

**Comment by Lruihao** [comment]
authorLink  在 https://github.com/hugo-fixit/FixIt/pull/288 中已被删除

<img width="798" alt="image" src="https://user-images.githubusercontent.com/33419593/227773987-f24919d4-49d7-4d39-bc72-2246b546a755.png">
