### ISSUE TITLE
[BUG] 当cookie consent加载失败时目录 & 回到顶部 不显示

### ISSUE THREAD

**Issue by du33169** [hugo-fixit/FixIt#314]
### Describe the bug 描述你遇到的错误

在开启cookieconsent的同时，如果使用[I don't care about cookie](https://www.i-dont-care-about-cookies.eu/)之类的浏览器插件访问网站，或者因为其他原因（例如单独配置的CDN失效）导致cookieconsent.min.js无法加载时，会导致页面的目录和回到顶部按钮不显示。

根据报错可以定位到是由于[theme.js](https://github.com/hugo-fixit/FixIt/blob/ff95cfaed7a9cebe4e14be3d4cbf58f2d107c169/src/js/theme.js#L1316)中，当cookieconsent加载失败时，抛出异常导致后续步骤无法执行。

```js
init() {
    try {
      if (this.config.encryption) {
        this.initFixItDecryptor();
      } else if (!this.config.encryption?.all) {
        this.initTwemoji();
        this.initDetails();
        this.initLightGallery();
        this.initHighlight();
        this.initTable();
        this.initHeaderLink();
        this.initMath();
        this.initMermaid();
        this.initEcharts();
        this.initTypeit();
        this.initMapbox();
        this.initPangu();
      }
      this.initThemeColor();
      this.initSVGIcon();
      this.initMenu();
      this.initSwitchTheme();
      this.initSearch();
      this.initCookieconsent();//here
      this.initSiteTime();
      this.initServiceWorker();
      this.initWatermark();
      this.initMDevtools();
      this.initAutoMark();
      this.initReward();

      window.setTimeout(() => {
        this.initComment();
        if (!this.config.encryption?.all) {
          this.initToc();
          this.initTocListener();
        }
        this.onScroll();
        this.onResize();
        this.onClickMask();
        this.beforeprint();
      }, 100);
    } catch (err) {
      console.error(err);
    }
  }
```

### Expected behavior 期待的行为

对于cookieConsent这类提供额外功能且独立于其他部分的第三方资源的初始化过程，是否可以改为**异步执行**以避免某个模块的资源加载失败导致影响页面功能？

这应该也有助于提供页面加载速度。

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/46591250/229272955-cbd4ee71-eacb-4344-86a4-a0a3c5724a57.png)

![image](https://user-images.githubusercontent.com/46591250/229272054-5ce4116e-f6aa-4ad4-bd08-14d0cbd613fd.png)

**Comment by Lruihao** [comment]
先修复 cookie consent 加载失败导致的阻断报错，第三方资源初始化改为异步执行进程延后，后续版本 JS 整体重构再考虑。
