### ISSUE TITLE
[FEATURE] Possibility to order link in params.social

### ISSUE THREAD

**Issue by savbran** [hugo-fixit/FixIt#320]
### Describe the feature you want 描述你的功能需求

Currently, it is not possible to order params.social. I tried to do that in config.tom but the theme always uses its order.

Can you provide a custom order, for example changing the order in param.social list? Thanks in advance for the information you can provide.

**Comment by Lruihao** [comment]
try https://github.com/orgs/hugo-fixit/discussions/251
