### ISSUE TITLE
[FEATURE] render title for codeblock

### ISSUE THREAD

**Issue by hack-scan** [hugo-fixit/FixIt#330]
### Describe the feature you want 描述你的功能需求

作者你好，非常感谢你能为广大作者开发这个主题！

我有一些要求，由于自身能力不足需要你来帮我们来完成！

1.  代码名添加，例如demo.py（当然可以根据后缀名自动设置代码高亮那更好不过）

2.  添加下载链接，markdown语法本身是没有的
![Uploading image.png…]()
类似于这样，希望都可以满足嘿嘿，作者辛苦了！

**Comment by Lruihao** [comment]
该功能已实现，对应分支 `v0.2.18-lts`

> 由于 1.0.0 大版本正在开发中，0.2.18 版本不再单独发布版本，所有修复更新全部更新在分支 `v0.2.18-lts`

**Comment by Lruihao** [comment]
已合并到 0.3.0
