### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by kakayikaka** [hugo-fixit/FixIt#334]
### Describe the bug 描述你遇到的错误

当开启 fingerprint 时，html 生成的 integrity  与文件实际哈希码不同

Failed to find a valid digest in the 'integrity' attribute for resource 'https://xxx/js/theme.min.81e852a4cdb2xxxxx3614f93188bc062ae547de10130d3.js' with computed SHA-256 integrity 'PDEns+m+iBIyUUbiXJeu/rZMOAAXdf7cSNPbOHubL8g='. The resource has been blocked.

### Expected behavior 期待的行为

可以正常启用 fingerprint

### Screenshots 屏幕截图

![image](https://github.com/hugo-fixit/FixIt/assets/136681872/9d604da3-f4b6-46c9-b607-ce6ab6630ee3)

**Comment by Lruihao** [comment]
未知原因，暂时无法复现
