### ISSUE TITLE
[FEATURE] 添加Artalk评论支持

### ISSUE THREAD

**Issue by fulyaec** [hugo-fixit/FixIt#343]
### Describe the feature you want 描述你的功能需求

非常好用的主题👍👍👍

希望能添加artalk评论插件支持 https://github.com/ArtalkJS/Artalk

### Useful reference 有价值的参考

https://github.com/ArtalkJS/Artalk

**Comment by Lruihao** [comment]
该功能已存在 https://github.com/hugo-fixit/FixIt/issues/54
