### ISSUE TITLE
[BUG] featuredImage: 文章的特色图片 在显示器高分辨率下不显示

### ISSUE THREAD

**Issue by Meilinhost** [hugo-fixit/FixIt#346]
### Describe the bug 描述你遇到的错误

用 featuredImage: "Oracle.webp" 方式调用本地特色图片 低分辨率正常，高分辨率不显示

比如路径 ：
/posts/文章文件夹/Oracle.webp

低分辨率 电脑&手机都可以正常显示，高分辨率就不会显示,读取路径也发生变化，变成了

https://网站/Oracle.webp

BUG出现在在高分辨率的显示器上 比如：1536*864 125%缩放或者更高

复现：可以到 [xidcn.com](https://xidcn.com)  查看

### Expected behavior 期待的行为

等大佬修复

### Screenshots 屏幕截图

高分辨率下出问题的截图

![picimage (1)](https://github.com/hugo-fixit/FixIt/assets/3524108/c61884b4-96b3-4072-aaf0-dee43c5a0102)

F12信息

![2](https://github.com/hugo-fixit/FixIt/assets/3524108/baf3161f-0b80-4b2f-9525-2a330cb3a44d)

### Build Environment 构建环境

系统：debian11
hugo：0.115.3
主题：FixIt 0.2.18

### Preview Environment 预览环境

复现方式：
设置分辨率1536*864 125% 缩放或者更高
![wt](https://github.com/hugo-fixit/FixIt/assets/3524108/5720e84d-1f82-40a4-84fd-d1748a4a2b4f)
打开 [xidcn.com](https://xidcn.com)  查看，此时特色图片出问题

![wt](https://github.com/hugo-fixit/FixIt/assets/3524108/32cc39d1-13b6-42fd-85fe-d3e3d479671f)

**Comment by Lruihao** [comment]
已修复，麻烦测试一下@Meilinhost

**Comment by Meilinhost** [comment]
> 已修复，麻烦测试一下@Meilinhost

主题升级到最新的版本
测试分辨率 125% 缩放 图片依旧丢失
![批注 2023-10-24 195000](https://github.com/hugo-fixit/FixIt/assets/3524108/bad5bdf0-4aa2-4077-86fe-fde5f50fd0d9)

**Comment by Lruihao** [comment]
> > 已修复，麻烦测试一下@Meilinhost
> 
> 
> 
> 主题升级到最新的版本
> 
> 测试分辨率 125% 缩放 图片依旧丢失
> 
> ![批注 2023-10-24 195000](https://github.com/hugo-fixit/FixIt/assets/3524108/bad5bdf0-4aa2-4077-86fe-fde5f50fd0d9)

是更新到v0.2.18-lts这个分支吗，顺便可以提供一下这篇文章的数据吗？

**Comment by Meilinhost** [comment]
@Lruihao 
> 是更新到v0.2.18-lts这个分支吗，顺便可以提供一下这篇文章的数据吗？

是的，v0.2.18-lts分支
我打包好了文章数据，你可以复现试试
https://xidcn.com/123.tar.gz

**Comment by Lruihao** [comment]
经测试已解决
