### ISSUE TITLE
[BUG] 使用外部图床时，无法根据标题索引正确转跳至文章指定位置

### ISSUE THREAD

**Issue by For-December** [hugo-fixit/FixIt#348]
### Describe the bug 描述你遇到的错误

如题，当我使用了其他域的图床时，无论是通过 URL 最后一级，还是通过点击右侧的标题索引，在文章内跳转都会有偏差

### Expected behavior 期待的行为

等大佬修复

### Screenshots 屏幕截图

![image](https://github.com/hugo-fixit/FixIt/assets/100057209/e7d73a92-5cc7-4528-b152-ac12b6245a32)

### Build Environment 构建环境

hugo：0.115.4_extended
主题：FixIt 0.2.18

### Preview Environment 预览环境

- OS: [Windows 10]
- Brower [Chrome, Edge]

### Additional Information 补充信息

默认配置文件

**Comment by Lruihao** [comment]
目前有两种解决办法：

1. 使用 image shortcode 手动为图床图片设置宽高
2. 开启 `params.cacheRemoteImages` 参数，详见 #362

**Comment by Lruihao** [comment]
测试文章：https://fixit-cd48eu0dy-cell-x.vercel.app/zh-cn/tests/markdown/

**Comment by Lruihao** [comment]
原 LoveIt 希望支持多分辨率显示，并让浏览器计算出正在显示的显示器的分辨率（`size="auto"`），然后显示 srcset 引用的最适合的图片。但 FixIt 希望**每个人在屏幕上看到的图片的实际尺寸（CSS像素）是相同的**，所以在处理懒加载图片的大小时，应该保持和加载后的实际显示图片保持相同的处理逻辑。

参考：[分辨率切换：相同的尺寸，不同的分辨率](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#%E5%88%86%E8%BE%A8%E7%8E%87%E5%88%87%E6%8D%A2%EF%BC%9A%E7%9B%B8%E5%90%8C%E7%9A%84%E5%B0%BA%E5%AF%B8%EF%BC%8C%E4%B8%8D%E5%90%8C%E7%9A%84%E5%88%86%E8%BE%A8%E7%8E%87)

**Comment by Lruihao** [comment]
测试文章：https://fixit-nt2t6uxm7-cell-x.vercel.app/zh-cn/tests/markdown/
