### ISSUE TITLE
[BUG] DEPRECATED: Kind "taxonomyterm" used in outputs configuration is deprecated, use "taxonomy" instead.

### ISSUE THREAD

**Issue by blusewill** [hugo-fixit/FixIt#354]
### Describe the bug 描述你遇到的错误

So I just saw this error when I am trying to use ``hugo server -FD`` command but after this hugo update it warns me taxonomyterm is outdated though the website is fine but I hope this won't be a issue in the future update

### Expected behavior 期待的行为

when I run hugo as a preview server there shouldn't be 
``DEPRECATED: Kind "taxonomyterm" used in outputs configuration is deprecated, use "taxonomy" instead.``

### Screenshots 屏幕截图

![image](https://github.com/hugo-fixit/FixIt/assets/62820836/41fae8aa-d085-491d-b1b8-863968cbabba)

### Preview Environment 预览环境

Hugo Version - hugo v0.117.0+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs
System - Arch Linux x86_64
Kernel - 6.4.11-arch2-1

**Comment by Lruihao** [comment]
To avoid the "taxonomyterm" warning, change the outputs configuration, like this [outputs.toml](https://github.com/hugo-fixit/docs/blob/6da7e7b341e1d302258cc59397bb032526df7f1e/config/_default/outputs.toml):

```diff
# -------------------------------------------------------------------------------------
# Customizing Output Formats | 自定义输出格式
# See: https://gohugo.io/templates/output-formats/#customizing-output-formats
# -------------------------------------------------------------------------------------

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
home = ["HTML", "RSS", "JSON", "BaiduUrls"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
- taxonomy = ["HTML", "RSS"]
- taxonomyTerm = ["HTML"]
+ taxonomy = ["HTML"]
+ term = ["HTML", "RSS"]
```

**Comment by blusewill** [comment]
Got it.
Will try it later tonight
