### ISSUE TITLE
[FEATURE] 首页文章按修改日期排序

### ISSUE THREAD

**Issue by user-xiaosi** [hugo-fixit/FixIt#356]
### Describe the feature you want 描述你的功能需求

希望增加一个功能，在首页显示的文章能按最后修改日期排序

**Comment by Lruihao** [comment]
如果首页文章按照修改日期排序，这会破坏现有的文章内的上一篇下一篇的逻辑顺序，所以该需求不做处理。

但是，如果你确实想这样做，你可以复制 `blog/themes/FixIt/layouts/index.html` 到 `blog/layouts/index.html`，然后添加如下三行代码：

<img width="657" alt="image" src="https://github.com/hugo-fixit/FixIt/assets/33419593/cc6586aa-ac75-41d0-a12c-b46debbe46e5">
