### ISSUE TITLE
[BUG] 部分友链头像获取失败

### ISSUE THREAD

**Issue by inuyasha-660** [hugo-fixit/FixIt#369]
### Describe the bug 描述你遇到的错误

1. 一些友链的头像可以正常访问，但加上``?size=small``或``?size=large``之后就无法获取了
友链好像会获取三个尺寸的头像，只要有一个访问不了就整个不显示，只能``hugo``后手动去``public/frineds/index.html``删除后面的``?size=small``
2. 如果只有三个或两个友链，排序是左边到右边到中间，是故意这么排的吗

### Expected behavior 期待的行为

头像正常显示，友链从左到右排序

### Screenshots 屏幕截图

![截图 2023-11-04 12-57-43](https://github.com/hugo-fixit/FixIt/assets/103230572/b4e9f0dd-77bf-408d-8b5d-af74ceb61be5)

### Build Environment 构建环境

Debian
v0.2.18-lts.3
hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended linux/amd64 BuildDate=2023-11-01T17:57:00Z VendorInfo=snap:0.120.3

### Preview Environment 预览环境

Debian
Chrome

**Comment by Lruihao** [comment]
有预览环境吗？

**Comment by inuyasha-660** [comment]
> 有预览环境吗？

https://blog.inuya.ltd/friends/

**Comment by Lruihao** [comment]
@inuyasha-660 排序规则是使用了 flex 布局的 `justify-content: space-between;` 特性。图片 url 加上 `?size=xxx` 后可能会导致找不到图片的问题，我晚点发个版本修复一下。

**Comment by inuyasha-660** [comment]
好，感谢您

**Comment by Lruihao** [comment]
已修复，将在 `v0.2.18-lts.4` 版本发布。
