### ISSUE TITLE
valine评论emoji显示异常

### ISSUE THREAD

**Issue by inuyasha-660** [hugo-fixit/FixIt#376]
### Describe the bug 描述你遇到的错误

使用valine评论emoji后，预览和评论的emoji会被拉长，但选择界面是正常的
在hexo时没有这个问题，不确定是否为主题的原因，尝试更换浏览器和自定义emoji数据文件无效
虽然是小问题，但看着挺折磨人的

### Expected behavior 期待的行为

emoji正常显示

### Screenshots 屏幕截图

![IMG_20231106_203702](https://github.com/hugo-fixit/FixIt/assets/103230572/0ef59f2c-409d-465c-bd3f-6cbbe54d1d92)

### Build Environment 构建环境

Debian
V0.2.18-lts.4
hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended linux/amd64 BuildDate=2023-11-01T17:57:00Z VendorInfo=snap:0.120.3

### Preview Environment 预览环境

Debian Android
Yandex 自带浏览器 1dm+

https://blog.inuya.ltd/posts/hugo/

**Comment by Lruihao** [comment]
1. emoji 被拉长问题已修复，预计 `v0.2.18-lts.5` 发布
2. valine 自定义表情，可通过 valine 的 emoji 字段指定 emoji 数据文件名称，默认是 "google.yml"

     主题内置的表情有：["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
     
3. 例如，我想自定义一个 bilibili 的表情，先在自己博客创建文件 `assets/lib/valine/emoji/bilibili.yml`，写入如下内容：

     ```yml
      emojiCDN: '//i0.hdslb.com/bfs/emote/'
      emojiMaps:
        tv_doge: 6ea59c827c414b4a2955fe79e0f6fd3dcd515e24.png
        tv_亲亲: a8111ad55953ef5e3be3327ef94eb4a39d535d06.png
        tv_偷笑: bb690d4107620f1c15cff29509db529a73aee261.png
        tv_再见: 180129b8ea851044ce71caf55cc8ce44bd4a4fc8.png
        tv_冷漠: b9cbc755c2b3ee43be07ca13de84e5b699a3f101.png
        tv_发怒: 34ba3cd204d5b05fec70ce08fa9fa0dd612409ff.png
        tv_发财: 34db290afd2963723c6eb3c4560667db7253a21a.png
        tv_可爱: 9e55fd9b500ac4b96613539f1ce2f9499e314ed9.png
        tv_吐血: 09dd16a7aa59b77baa1155d47484409624470c77.png
        tv_呆: fe1179ebaa191569b0d31cecafe7a2cd1c951c9d.png
        tv_呕吐: 9f996894a39e282ccf5e66856af49483f81870f3.png
        tv_困: 241ee304e44c0af029adceb294399391e4737ef2.png
        tv_坏笑: 1f0b87f731a671079842116e0991c91c2c88645a.png
        tv_大佬: 093c1e2c490161aca397afc45573c877cdead616.png
        tv_大哭: 23269aeb35f99daee28dda129676f6e9ea87934f.png
        tv_委屈: d04dba7b5465779e9755d2ab6f0a897b9b33bb77.png
        tv_害羞: a37683fb5642fa3ddfc7f4e5525fd13e42a2bdb1.png
        tv_尴尬: 7cfa62dafc59798a3d3fb262d421eeeff166cfa4.png
        tv_微笑: 70dc5c7b56f93eb61bddba11e28fb1d18fddcd4c.png
        tv_思考: 90cf159733e558137ed20aa04d09964436f618a1.png
        tv_惊吓: 0d15c7e2ee58e935adc6a7193ee042388adc22af.png
        # 更多表情映射……
     ```
     
     然后修改 valine 配置 `emoji = "bilibili.yml"` 即可。
