### ISSUE TITLE
[FEATURE] Add support for simpler admonition sytax

### ISSUE THREAD

**Issue by HCPlantern** [hugo-fixit/FixIt#406]
### Describe the feature you want 描述你的功能需求

希望能够简化 admonition 的语法，或者提供另一个语法选择。

现在的语法：

```
{{< admonition tip "This is a tip" false >}}
一个 **技巧** 横幅
{{< /admonition >}}
```

希望能够提供的语法：

```
> [!tip]- This is a tip
> 一个 **技巧** 横幅
```

### Useful reference 有价值的参考

可以参考 Obsidian 的 callout 语法：https://help.obsidian.md/Editing+and+formatting/Callouts

**Comment by HCPlantern** [comment]
补充一下，Github 目前也已支持这种语法，见 https://github.com/orgs/community/discussions/16925

**Comment by Lruihao** [comment]
> 补充一下，Github 目前也已支持这种语法，见 https://github.com/orgs/community/discussions/16925

我有关注到这个，只是一直没有时间来开发这个需求。

**Comment by Lruihao** [comment]
Hugo 已支持 blockquote render hook，这个需求的实现将变得非常简单。

https://gohugo.io/render-hooks/blockquotes/

**Comment by Lruihao** [comment]
已支持，详见文档 https://fixit.lruihao.cn/documentation/content-management/markdown-syntax/extended/#alerts

**Comment by Lruihao** [comment]
在 0.3.13 版本支持兼容 Obsidian 的 callout 语法。
