### ISSUE TITLE
[BUG] 部分加密移动端无法点击确认

### ISSUE THREAD

**Issue by gengyj16** [hugo-fixit/FixIt#410]
### Describe the bug 描述你遇到的错误

文章内有多个输入框情况下使用部分加密，PC端可以正常输入密码后回车解密，移动端显示为下一项，光标会移动到下个输入处，内容没有解密

### Expected behavior 期待的行为

移动端显示确定按钮而不是下一项，或者密码输入框旁边增加一个解密按钮/失去焦点后自动尝试使用已输入内容解密（不被键盘行为影响）

### Screenshots 屏幕截图

![Screenshot_2024-01-26-13-55-26-46_32cba261fc08a501ce70de75bdbe2575_Mosaic_13_55_49](https://github.com/hugo-fixit/FixIt/assets/22300654/2c35dfec-e328-4237-acba-1003a4b6c930)

### Build Environment 构建环境

- OS: Ubuntu Focal 20.04
- Theme version: [dd4f422](https://github.com/hugo-fixit/FixIt/commit/dd4f422dba1769f0540c80df91c4ac595bed0c14)
- Hugo version: 0.121.1

### Preview Environment 预览环境

- OS: Android
- Browser: Chrome

### Additional Information 补充信息

可供复现问题的博客[链接](https://blog.0to1.cf/posts/tools/)

另外演示站点的[内容加密](https://fixit.lruihao.cn/zh-cn/documentation/content-management/encryption/)，全文解密后内文的部分加密无法解密（PC和移动端均是）

**Comment by Lruihao** [comment]
ios自带的输入法是 return。这个有时间再改一下。

**Comment by gengyj16** [comment]
另外关于上面结尾处提到的

> 演示站点的[内容加密](https://fixit.lruihao.cn/zh-cn/documentation/content-management/encryption/)，全文解密后内文的部分加密无法解密（PC和移动端均是）

在自己博客上复制了一份[测试](https://blog.0to1.cf/posts/content-encryption/)，全文加密情况下的部分加密是正常的；但是如果不使用全文加密，[仅部分加密](https://blog.0to1.cf/posts/content-encryption-part/)，文章内样式异常（admition无法展开/折叠、代码块的头部和右上角按钮缺失、移动端-目录无法展开/折叠）

**Comment by Lruihao** [comment]
所有 BUG 都已修复，另外：

1. 部分加密在设计之初就是设定为临时的解密，所以没有记忆功能
2. #437
