### ISSUE TITLE
[BUG] 图片显示问题

### ISSUE THREAD

**Issue by Alfly** [hugo-fixit/FixIt#411]
### Describe the bug 描述你遇到的错误

图片显示比例出现问题

使用原生 markdown ![]() 会出现这个问题，换成 shortcode {{< figure >}} 则没有这个问题

### Expected behavior 期待的行为

fix

### Screenshots 屏幕截图

<img width="726" alt="image" src="https://github.com/hugo-fixit/FixIt/assets/49281418/ab7bcd78-cdfa-4839-946d-6a6ffb33d620">

### Build Environment 构建环境

hugo v0.120.4
fixit v0.3.0

### Additional Information 补充信息

[复现 demo](https://lruihao.cn/posts/cognitive-complexity/)

**Comment by Lruihao** [comment]
BUG 原因，Chrome (121.0.6167.85) 开始，给 img size="auto" 加了一个默认样式导致图片宽高比异常。

![0e5d5927f169e58ff02a8d9794547c20](https://github.com/hugo-fixit/FixIt/assets/33419593/32846da4-042b-4075-b0b0-3b8433abed51)
