### ISSUE TITLE
[FEATURE] change text color of links in "See Also"

### ISSUE THREAD

**Issue by wanghuibin0** [hugo-fixit/FixIt#412]
### Describe the feature you want 描述你的功能需求

I recommand adding the feature that users can configure the text color of links in "See Also".
Now the default color is black and I don't find any configuration entry to change it.
Is this feature possible? Thanks.

**Comment by Lruihao** [comment]
You can chang any color in your `assets/css/_custom.scss`
```css
#see-also {
  color: red; 
}
```
