### ISSUE TITLE
[BUG] 使用artalk2.8.2 docker版本，调用出现404，已初步发现问题，求优化解决

### ISSUE THREAD

**Issue by a512471** [hugo-fixit/FixIt#415]
### Describe the bug 描述你遇到的错误

- 自部署了artalk2.8.2，使用fixlt配置模板启用artalk后页面出现404错误，如下图：

![image](https://github.com/hugo-fixit/FixIt/assets/17682928/146678be-3f52-484d-9549-6f8da9d19980)

- 查看artalk后台报错如下：

![image](https://github.com/hugo-fixit/FixIt/assets/17682928/cd3c9c04-bce1-4d8b-a39b-75ffdafded07)

- 然后我试着使用artalk官方推荐的前端引用直接修改hugo的public中页面源码，写法如下：

![image](https://github.com/hugo-fixit/FixIt/assets/17682928/dfcb0710-4ed7-4008-b1f0-f279ec3e66d3)

- 之后刷新页面发现正常了，可以评论：

![image](https://github.com/hugo-fixit/FixIt/assets/17682928/5493dac9-569d-442a-a635-8a06d7ea138f)

- 推测应该市fixlt中artalk模板使用的内置前端 CSS、JS 资源导致的，版本比较老

### Expected behavior 期待的行为

希望fixlt对artalk支持的模板上能再改一改，artalk官网现在使用的css和js文件直接在后端提供，不需要内置到fixlt中了，这样灵活性更高点
![image](https://github.com/hugo-fixit/FixIt/assets/17682928/8764d084-b0d1-4931-a839-73c959fddfd4)

**Comment by JamesFlare1212** [comment]
暂时可以手动在这里改一下

https://github.com/hugo-fixit/FixIt/blob/c9af0b9018ffb87b59b3295ca740be54682d08ab/layouts/partials/single/comment.html#L18-L20

**Comment by Lruihao** [comment]
抱歉，最近业余时间都在写 FixIt 的文档，这个问题我下个 fix 版本改一下。
