### ISSUE TITLE
Please don't use symbolic links 

### ISSUE THREAD

**Issue by jmooring** [hugo-fixit/FixIt#419]
### Describe the bug 描述你遇到的错误

Please don't use symbolic links in your theme:

![image](https://github.com/hugo-fixit/FixIt/assets/335669/9c871fe9-76e8-4696-bff4-ed15388697ef)

Instead, instruct your theme users to do something like:

```text
cd demo
hugo server --themesDir ../..
```

Why? Recursion.

![image](https://github.com/hugo-fixit/FixIt/assets/335669/7192557a-3239-455e-ace6-1ba1f0f4ae9a)

**Comment by Lruihao** [comment]
Thanks for your feedback.
