### ISSUE TITLE
[BUG] gitalk ·评论区颜色模式无法跟随深色模式改变

### ISSUE THREAD

**Issue by williamlfang** [hugo-fixit/FixIt#424]
### Describe the bug 描述你遇到的错误

gitalk ·评论区颜色模式无法跟随深色模式改变

### Expected behavior 期待的行为

gitalk ·评论区颜色模式跟随深色模式改变

### Screenshots 屏幕截图

![2024-03-17_22-18](https://github.com/hugo-fixit/FixIt/assets/5860824/2afa7eeb-757b-4885-bb8a-6ce955ea16a5)

**Comment by Lruihao** [comment]
gitalk 自身未带有深色模式，https://github.com/gitalk/gitalk/issues/567
