### ISSUE TITLE
[BUG] Some problem ...

### ISSUE THREAD

**Issue by hzp2333** [hugo-fixit/FixIt#426]
### Describe the bug 描述你遇到的错误

hugo自带的目录系统可以在文章页面生成目录，点击不同的子标题会跳转到对应部分。
**不知道为什么？我的博客中文页面无法实现目录跳转，但是英文页面可以正常跳转。**
![9773c9cdf18cb7e866628c0f8ad3f35](https://github.com/dillonzq/LoveIt/assets/79459902/a90e21ab-4529-4224-a095-32abfa47b590)
同时，当我在本地预览（localhost:1313）时，英文和中文的文章目录跳转都是正常的。

### Expected behavior 期待的行为

是什么因素导致本地和正式上传后的情况不同呢111？
如何修正中文目录的情况呢？
十分感谢您的回答！

### Build Environment 构建环境

 Windows 11 +loveit主题+hugo扩展版
使用的hugo默认的目录，没有额外设置什么

### Additional Information 补充信息

网站地址：https://blog.huaxiangshan.com/

**Comment by Lruihao** [comment]
我看你的主题是 DoIt 😂，去 [DoIt](https://github.com/HEIGE-PCloud/DoIt/discussions) 社区问问看...
