### ISSUE TITLE
[BUG] 部分加密无法正常解密

### ISSUE THREAD

**Issue by geekswg** [hugo-fixit/FixIt#429]
### Describe the bug 描述你遇到的错误

预览地址
https://fixit.lruihao.cn/zh-cn/documentation/content-management/encryption/#partial-encryption
，我自己的demo也是，输入密码后回车没有反应。
为了兼容性建议添加个解密按钮来点击触发。

### Expected behavior 期待的行为

部分加密内容可以，正常解密显示

**Comment by Lruihao** [comment]
Duplicate with #410
