### ISSUE TITLE
[BUG] 在配置好的前提下 toc 不显示五六级标题

### ISSUE THREAD

**Issue by YangHgRi** [hugo-fixit/FixIt#454]
### Describe the bug 描述你遇到的错误

如题

### Expected behavior 期待的行为

正常显示

### Screenshots 屏幕截图

![image](https://github.com/hugo-fixit/FixIt/assets/57426791/c9334ac3-ef8a-4dab-9fc5-eb3a9fa9320e)

![image](https://github.com/hugo-fixit/FixIt/assets/57426791/39c11a3f-5ac7-4cf8-91be-e1d3a32d409a)

### Build Environment 构建环境

hugo 0.127.0
theme 0.3.7

**Comment by Lruihao** [comment]
目录内容由 hugo 渲染而成，注意内容层级连贯应该不会出现问题。例如：https://pre.fixit.lruihao.cn/zh-cn/tests/markdown/
