### ISSUE TITLE
[FEATURE] 隐藏代码块标题 | Hide block title

### ISSUE THREAD

**Issue by Tim-Saijun** [hugo-fixit/FixIt#462]
### Describe the feature you want 描述你的功能需求

希望可以自定义配置隐藏代码块的标题，否则大量代码堆积看起来有点乱

---
I hope to customize the title of the hidden code block, otherwise a large number of code stacks will look a bit messy, [reference effect](https://nbviewer.org/url/jakevdp.github.io/downloads/notebooks/XKCD_plots.ipynb)

![image](https://github.com/user-attachments/assets/7fb462c8-a818-4965-8e36-03dd421c8172)

### Useful reference 有价值的参考

[参考效果](https://nbviewer.org/url/jakevdp.github.io/downloads/notebooks/XKCD_plots.ipynb)

**Comment by Lruihao** [comment]
好想法👍

**Comment by Lruihao** [comment]
当 `page.code.enable` 时不显示，代码块 header (复制编辑等功能同时关闭)
```toml
[params.page.code]
  enable = false
```

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/d629f0c8-281e-4480-a549-f6cdb86c7219">

**Comment by Lruihao** [comment]
额外增加针对单个代码块的参数：

<img width="823" alt="image" src="https://github.com/user-attachments/assets/5d399743-69d2-473c-8a99-60a94705363a">
