### ISSUE TITLE
[FEATURE] SEO的keywords和description优化

### ISSUE THREAD

**Issue by Tim-Saijun** [hugo-fixit/FixIt#466]
### Describe the feature you want 描述你的功能需求

现在的SEO做法是，虽然每篇网页都有Title, keywords, description, 但整个站点所有页面的keywords, description都是相同的，这点不利于SEO。例如在某个文章页面，这两项与当前文章毫无关系，是设置的整站关键词。
![image](https://github.com/user-attachments/assets/b6c22ca0-63f3-4441-a511-8ef486705894)
希望能给每篇文章设置单独的关键词和描述。当用户没有提供时，再使用整站的关键词作为默认值。

**Comment by Lruihao** [comment]
每个页面可以通过 front matter 单独设置 description和keywords

**Comment by Tim-Saijun** [comment]
> 每个页面可以通过 front matter 单独设置 description和keywords

感谢，回去看文档了
