### ISSUE TITLE
[BUG] FixIt 主题完全兼容 Hugo 的多语言模式zh-cn必须修改为是zh才会显示简体中文

### ISSUE THREAD

**Issue by scdsskj** [hugo-fixit/FixIt#524]
### Describe the bug 描述你遇到的错误

 [languages.zh-cn]
    weight = 2
    title = "我的 Hugo FixIt 网站"
    # 网站语言，仅在这里 CN 大写
    languageCode = "zh-CN"
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3

### Expected behavior 期待的行为

[languages.zh]
    weight = 2
    title = "我的 Hugo FixIt 网站"
    # 网站语言，仅在这里 CN 大写
    languageCode = "zh-CN"
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    [[languages.zh.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3

### Build Environment 构建环境

macOS15.1+hugo v0.136.4+FixIt v0.3.13+edge

### Additional Information 补充信息

希望作者更新并修复

**Comment by Lruihao** [comment]
中文就是对应 .zh-cn 后缀的配置，遇到什么问题吗。

**Comment by Lruihao** [comment]
根据 [RFC5646](https://datatracker.ietf.org/doc/html/rfc5646#section-2.1)，使用 `zh-cn` 表示简体中文是符合规范，也符合常用习惯的。
