### ISSUE TITLE
Image Link Rendering Issue w/ DuckDuckGo & Firefox

### ISSUE THREAD

**Issue by unnsse** [hugo-fixit/FixIt#526]
Am loving using Hugo and the FixIt theme for my website (https://unnsse.io) - thank you so much for creating and maintaining this very lovely and useful theme!

Started using Clicky for website analytics, by pasting in the tracking code on the same line as `Powered by`, but right after the `FixIt` logo separated with a `-`?`layouts/partials/footer.html`:

https://github.com/unnsse/unnsse.io/blob/81a44f654ab553e9c681953dc5326cc42fa3be32/layouts/partials/footer.html#L25-L26:

```javascript
- <a title="Google Analytics Alternative" href="https://clicky.com/101467984"><img alt="Clicky" src="//static.getclicky.com/media/links/badge.gif" border="0" /></a><script async data-id="101467984" src="//static.getclicky.com/js"></script>
```

Renders correctly via Safari & Chrome, but the image is bigger and appears misaligned:

`Safari`:
![footer_safari](https://github.com/user-attachments/assets/5aef0575-03ac-45b4-9f9a-bbf2a649a7cd)

`Chrome`:

![footer_chrome](https://github.com/user-attachments/assets/bafa084d-b575-457d-8ec5-5587d98c75df)

---

The other issue is that with`Firefox` & `DuckDuckGo`, the image doesn't render (not orange text or box surrounding the text) correctly:

`Firefox`:

![footer_firefox](https://github.com/user-attachments/assets/79411f4d-d31c-4df9-9d47-060f7cd89518)

`DuckDuckGo`:

![footer_duck](https://github.com/user-attachments/assets/c1eb07a1-2992-4e0e-a971-407e9d517c8a)

Question(s):

1. Why is it not rendering in `DuckDuckGo` and `Firefox` but is rendering correctly (with the exception of image size alignment) on Safari & Chrome?
2. Is there a way to create a custom `<div>` tag to auto-render this so it doesn't look misaligned and looks like the same size (on all browsers, including mobile)?

*Note*: Wasn't able to edit the title of this thread so apologize if the title is incorrect (referring to `localhost` instead of specific browsers).

_Originally posted by @unnsse in https://github.com/hugo-fixit/FixIt/discussions/525_

**Comment by Lruihao** [comment]
Sorry！I think this is a customized requirement, so it's not very suitable to be built into the theme. 
For your questions, it seems to be just a CSS issue, and you need to modify the style in `_custom.scss` until you are satisfied.
