### ISSUE TITLE
[BUG] Valine 评论系统不对友链页生效

### ISSUE THREAD

**Issue by LS-Shandong** [hugo-fixit/FixIt#527]
### Describe the bug 描述你遇到的错误

Valine 评论系统不对友链页生效，但 Giscus 可以生效。

**Comment by Lruihao** [comment]
经测试，valine 正常显示

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/76e41ee3-aabf-4ea4-95af-c9f022adc6b5">
