### ISSUE TITLE
[BUG] 代码块问题

### ISSUE THREAD

**Issue by scdsskj** [hugo-fixit/FixIt#528]
### Describe the bug 描述你遇到的错误

代码块没有达到预期的效果

### Expected behavior 期待的行为

![屏幕截图_27-10-2024_0256_fixit lruihao cn](https://github.com/user-attachments/assets/c5a9b74e-0e21-4ee7-a264-f0c9e2f68b55)
代码块不是应该这样吗？

### Screenshots 屏幕截图

![屏幕截图_26-10-2024_234423_192 168 101 12](https://github.com/user-attachments/assets/fa123219-de7c-42a3-b406-34f902fb0359)

### Build Environment 构建环境

MacOS15.1+hugo v0.136.5-extended+Fixit V0.3.13-dev

### Preview Environment 预览环境

![屏幕截图 2024-10-27 000749](https://github.com/user-attachments/assets/f4cd61e4-c808-4f6f-bb6d-0aa12a6b5ffc)

### Additional Information 补充信息

# Code wrapper config
    [params.page.code]
      # FixIt 0.3.9 | NEW whether to enable the code wrapper
      enable = true
      # whether to show the copy button of the code wrapper
      copy = true
      # FixIt 0.2.13 | NEW whether to show the edit button of the code wrapper
      edit = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10

**Comment by Lruihao** [comment]
把这个加上就好了。

```
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"

```
