### ISSUE TITLE
[FEATURE] 希望可以增加更多形式的复选框

### ISSUE THREAD

**Issue by deequoique** [hugo-fixit/FixIt#532]
### Describe the feature you want 描述你的功能需求
增加更多的- [ ]复选框，给博客提供更美观的效果
### Useful reference 有价值的参考
一个obsidian主题[相关内容的介绍](https://github.com/AnubisNekhet/AnuPpuccin/tree/main#custom-checkboxes--speech-bubbles)
![image](https://github.com/user-attachments/assets/276082e3-6f71-4acb-b63f-5dc85ffb62f4)

- [Obsidian Task lists](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Task+lists)
- [其代码实现](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/src/modules/Features/custom-checkboxes.scss)

**Comment by Lruihao** [comment]
我觉得这是一个很棒的功能！但是考虑到通用性，FixIt 主题目前暂时只内置了以下几种类型：

```md
- [ ] Unchecked
- [x] Checked
- [/] In Progress
- [-] Cancelled
- [<] Scheduled
- [>] Rescheduled
- [!] Important
- [?] Question
```

呈现效果如下：

<img width="452" alt="image" src="https://github.com/user-attachments/assets/88d5cb36-404d-4962-8ba7-4e28ac4bc63c">

如果需要自定义任务列表的类型，详见完整的文档：[Extended Markdown Syntax - Task Lists](http://fixit.lruihao.cn/documentation/content-management/markdown-syntax/extended/#task-lists)。
